version: '3'
services:
  
#################
#### Fronted
#################

  frontend_webserver:
    container_name: frontend_webserver
    restart: always
    build:
      context: ./frontend/nodejs
      dockerfile: Dockerfile
    volumes:
      - ${FRONTEND_APPLICATION}:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - backend_webserver
    ports:
      - "${FRONTEND_APP_PORT}:3000"
    links:
      - backend_webserver
    networks:
      - app-network


#################
#### Backend
#################

# PHP-FPM
  backend_php-fpm:
    container_name: backend_php-fpm
    restart: always
    build:
      context: ./backend/php-fpm
      args:
          - INSTALL_GD=${PHP_FPM_INSTALL_GD}
          - INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
          - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
          - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
          - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
          - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
          - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
          - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
          - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
          - INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
          - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
          - INSTALL_OPENSSL=${PHP_FPM_INSTALL_OPENSSL}
          - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
          - INSTALL_CALENDAR=${PHP_FPM_INSTALL_CALENDAR}
          - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
          - INSTALL_GETTEXT=${PHP_FPM_INSTALL_GETTEXT}
          - INSTALL_GMP=${PHP_FPM_INSTALL_GMP}
          - INSTALL_IMAGICK=${PHP_FPM_INSTALL_IMAGICK}
          - INSTALL_POSIX=${PHP_FPM_INSTALL_POSIX}
          - INSTALL_SHMOP=${PHP_FPM_INSTALL_SHMOP}
          - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
          - INSTALL_SOCKETS=${PHP_FPM_INSTALL_SOCKETS}
          - INSTALL_SYSVMSG=${PHP_FPM_INSTALL_SYSVMSG}
          - INSTALL_SYSVSEM=${PHP_FPM_INSTALL_SYSVSEM}
          - INSTALL_SYSVSHM=${PHP_FPM_INSTALL_SYSVSHM}
          - INSTALL_WDDX=${PHP_FPM_INSTALL_WDDX}

      dockerfile: Dockerfile  
    expose:
        - "9000"    
    volumes:
      - ${BACKEND_APPLICATION}:/var/www/html
    networks:
      - app-network


# NGINX Web Service - Backend
  backend_webserver:
    container_name: backend_webserver
    restart: always
    ##command: uname -a
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    volumes:
      - ${BACKEND_APPLICATION}:/var/www/html
      - ${BACKEND_NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${BACKEND_NGINX_SITES_PATH}:/etc/nginx/conf.d
    depends_on:
      - backend_php-fpm
      - backend_db
    ports:
      - "${BACKEND_NGINX_HOST_HTTP_PORT}:8000"
      - "${BACKEND_NGINX_HOST_HTTPS_PORT}:443"
    links:
      - backend_php-fpm
    networks:
      - app-network


## Database Service
  backend_db:
    container_name: backend_db
    build:
      context: ./backend/mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
       - "${MARIADB_PORT}:3306"
    volumes:
       - ${MARIADB_DATA}:/var/lib/mysql
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
##volumes:
##  dbdata:
##    driver: local
##  webdata:
##    driver: local
##    /
